const descriptors = [
  "Peaceful",
  "Golden",
  "Green",
  "Beautiful",
  "Sunny",
  "Quiet",
  "Hidden",
  "Royal",
  "Serene",
  "Tropical",
  "Fresh",
  "Scenic",
  "Lovely",
  "Calm",
  "Palm",
  "Riverside",
  "Cool",
  "Natural",
  "Cozy",
  "Amazing",
  "Majestic",
  "Charming",
  "Breezy",
  "Pleasant",
  "Wonderful",
  "Picturesque",
  "Refreshing",
  "Lush",
  "Tranquil",
  "Blissful",
  "Misty",
  "Rainy",
  "Warm",
  "Bright",
  "Shady",
  "Restful",
  "Relaxing",
  "Wild",
  "Rustic",
  "Traditional",
  "Cultural",
  "Local",
  "Pure",
  "Elegant",
  "Grand",
  "Delightful",
  "Adventurous",
  "Exciting",
  "Breathtaking",
  "Spectacular",
  "Magnificent",
  "Enchanting",
  "Fascinating",
  "Secret",
  "Remote",
  "Private",
  "Exclusive",
  "Premium",
  "Luxury",
  "Comfortable",
  "Friendly",
  "Welcoming",
  "Homely",
  "Family",
  "Romantic",
  "Mountain",
  "Forest",
  "River",
  "Savannah",
  "Coastal",
  "Island",
  "Lakeside",
  "Waterside",
  "Hilltop",
  "Sunrise",
  "Sunset",
  "Morning",
  "Evening",
  "Starry",
  "Moonlit",
  "African",
  "Nigerian",
  "Heritage",
];

const places = [
  "Grove",
  "Garden",
  "River",
  "Lake",
  "Hill",
  "Valley",
  "Forest",
  "Beach",
  "Palm",
  "Creek",
  "Haven",
  "Resort",
  "View",
  "Campsite",
  "Retreat",
  "Park",
  "Riverside",
  "Waterside",
  "Village",
  "Lodge",
  "Mountain",
  "Ranch",
  "Falls",
  "Lagoon",
  "Island",
  "Bay",
  "Cove",
  "Point",
  "Peak",
  "Ridge",
  "Trail",
  "Camp",
  "Meadow",
  "Woodland",
  "Jungle",
  "Rainforest",
  "Savannah",
  "Plains",
  "Hills",
  "Waterfall",
  "Spring",
  "Stream",
  "Pond",
  "Reservoir",
  "Lakeview",
  "Hillview",
  "Forestview",
  "Palmview",
  "Riverbank",
  "Riverbend",
  "Lakeside",
  "Hillside",
  "Mountainview",
  "Shore",
  "Oasis",
  "Sanctuary",
  "Hideaway",
  "Getaway",
  "Homestead",
  "Heritage",
  "Nature Camp",
  "Eco Camp",
  "Adventure Park",
  "Leisure Park",
  "Holiday Camp",
  "Family Resort",
  "Forest Camp",
  "River Camp",
  "Mountain Camp",
  "Hill Camp",
  "Lake Camp",
  "Palm Camp",
  "Savannah Camp",
  "Coastal Camp",
  "Rainforest Camp",
  "Nature Reserve",
  "Wildlife Camp",
  "Safari Camp",
  "Bush Camp",
  "Eco Lodge",
  "Nature Lodge",
  "River Lodge",
  "Forest Lodge",
  "Hill Lodge",
  "Lake Lodge",
  "Palm Lodge",
  "Waterside Lodge",
  "Garden Lodge",
  "Family Lodge",
  "Holiday Lodge",
  "Nature Retreat",
  "River Retreat",
  "Forest Retreat",
  "Hill Retreat",
  "Lake Retreat",
  "Palm Retreat",
  "Waterside Retreat",
  "Garden Retreat",
  "Nature Haven",
  "River Haven",
];

const descriptionFragments = [
  "Nestled just outside {city}, this spot offers a peaceful escape from the noise of the city.",
  "Popular with weekend campers from {state} State looking to unwind under the stars.",
  "Cool harmattan mornings here make for great fireside breakfasts.",
  "Surrounded by palm groves and farmland typical of the {state} countryside.",
  "A short drive from local markets, so you can pick up fresh produce before you set up camp.",
  "Known for its quiet nights, though the occasional distant generator hum reminds you you're still close to town.",
  "Great for first-time campers with accessible roads and a friendly local caretaker on site.",
  "The riverside breeze here makes evenings pleasant even in the dry season.",
  "A favorite stop for road-trippers passing through {state} on their way south.",
  "Local food vendors nearby serve up suya and roasted corn in the evenings.",
  "Red laterite soil and rolling hills give this site a distinct look you won't find further north.",
  "Rainy season turns the surrounding bush a deep, vivid green, so bring waterproof gear.",
  "A rustic site with basic facilities, best suited for campers who don't mind roughing it a little.",
  "Close enough to {city} for a supply run, far enough to feel properly away from it all.",
  "Locals sometimes stop by in the evenings to share stories around the fire, a great way to meet people from {state}.",
];

const buildDescription = (city, state) => {
  const shuffled = [...descriptionFragments].sort(() => 0.5 - Math.random());

  const chosen = shuffled.slice(0, 3);

  return chosen
    .map((frag) => frag.replace(/{city}/g, city).replace(/{state}/g, state))
    .join(" ");
};

const images = [
  "https://images.pexels.com/photos/9159989/pexels-photo-9159989.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/9160584/pexels-photo-9160584.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/6271505/pexels-photo-6271505.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/13788607/pexels-photo-13788607.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/12470606/pexels-photo-12470606.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/36495470/pexels-photo-36495470.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/20831770/pexels-photo-20831770.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/32973531/pexels-photo-32973531.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/18756397/pexels-photo-18756397.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/9160591/pexels-photo-9160591.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/17435176/pexels-photo-17435176.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/32973536/pexels-photo-32973536.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064887/pexels-photo-5064887.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/13415997/pexels-photo-13415997.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5065186/pexels-photo-5065186.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064896/pexels-photo-5064896.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064676/pexels-photo-5064676.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064884/pexels-photo-5064884.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064863/pexels-photo-5064863.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064892/pexels-photo-5064892.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064952/pexels-photo-5064952.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064878/pexels-photo-5064878.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5064897/pexels-photo-5064897.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/27528405/pexels-photo-27528405.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
  "https://images.pexels.com/photos/5589287/pexels-photo-5589287.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=800&h=600",
];

module.exports = {
  places,
  descriptors,
  descriptionFragments,
  buildDescription,
  images,
};
